### PR TITLE
add LogChimp product

### PR DESCRIPTION
**Pull request by mittalyashu**

### CODE REVIEW

**Comment by dend** [comment]
Like the contribution - thank you @mittalyashu. Some feedback:

1. Let's update the image to something that is descriptive. Right now this seems like a placeholder and it's very hard to tell what the product is about.
2. Filename should not contain `pod-`
3. Instead of open-source, can you please specify "Free (open-source/self-host)"?

Once the changes are in, we can merge.

**Comment by mittalyashu** [comment]
Hey @dend

Apologies for delay in response, can you re-open this PR, so that I can update the changes.

**Comment by dend** [comment]
@mittalyashu feel free to update - thanks again for the contribution!

**Comment by mittalyashu** [comment]
Thanks a lot.

**Pull request merged**
