### PR TITLE
added in Product Specs Template, I found it really helpful

### PR DESCRIPTION
**Pull request by xuanjin001**
I found a product spec template, I found it really helpful, and I found your list, so added it in here. Thank you.

### CODE REVIEW

**Comment by dend** [comment]
@xuanjin001 thanks for the contribution! Could you please revert the formatting changes, and just add the template to the "Additional Resources" section? https://github.com/dend/awesome-product-management#additional-resources

**Comment by xuanjin001** [comment]
@dend I just made the changes, moved the template to additional resources section. Please let me know if there is anything else. :)

**Comment by dend** [comment]
@xuanjin001 seems like there are quite a few changes that haven't been rolled back yet 😄

image

Highlighted areas are the ones that seem newly introduced with this PR.

**Comment by dend** [comment]
@xuanjin001 any thoughts on reverting the edits above? 😄

**Comment by xuanjin001** [comment]
@dend I think I know what happened, I have format beautifier installed in my local environment, so those count as spaces, when I save in vs code, it is automatically formatting it. Would you prefer your format?

**Comment by dend** [comment]
@xuanjin001 yes, please! Let's keep the format intact for now, but please do open a new pull request with just the addition of the template library, as we discussed.

**Pull request closed without merging**
